apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "koment.fullname" . }}
  labels: {{- include "koment.labels" . | nindent 4 }}
data:
  repositories.yaml: |
    repositories:
    {{- range .Values.repositories }}
      - id: {{ .id | quote }}
        {{- with .name }}
        name: {{ . | quote }}
        {{- end }}
        provider: {{ .provider | quote }}
        remote: {{ .remote | quote }}
        default_branch: {{ .defaultBranch | quote }}
        {{- if .default }}
        default: true
        {{- end }}
    {{- end }}
